// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/block/header/header.proto

package header

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	MerkleRoot    []byte                 `protobuf:"bytes,2,opt,name=merkle_root,json=merkleRoot,proto3" json:"merkle_root,omitempty"`
	PrevBlockHash []byte                 `protobuf:"bytes,3,opt,name=prev_block_hash,json=prevBlockHash,proto3" json:"prev_block_hash,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Height        uint64                 `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	Weight        uint64                 `protobuf:"varint,6,opt,name=weight,proto3" json:"weight,omitempty"`
	StateRoot     []byte                 `protobuf:"bytes,7,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Nonce         uint64                 `protobuf:"varint,8,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_block_header_header_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_block_header_header_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_block_header_header_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *Header) GetPrevBlockHash() []byte {
	if x != nil {
		return x.PrevBlockHash
	}
	return nil
}

func (x *Header) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Header) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Header) GetWeight() uint64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Header) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *Header) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_proto_block_header_header_proto protoreflect.FileDescriptor

const file_proto_block_header_header_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/block/header/header.proto\x12\x04core\"\xee\x01\n" +
	"\x06Header\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1f\n" +
	"\vmerkle_root\x18\x02 \x01(\fR\n" +
	"merkleRoot\x12&\n" +
	"\x0fprev_block_hash\x18\x03 \x01(\fR\rprevBlockHash\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x04R\x06height\x12\x16\n" +
	"\x06weight\x18\x06 \x01(\x04R\x06weight\x12\x1d\n" +
	"\n" +
	"state_root\x18\a \x01(\fR\tstateRoot\x12\x14\n" +
	"\x05nonce\x18\b \x01(\x04R\x05nonceBLZJgithub.com/andantan/p2p-pbft-modular-blockchain-network/proto/block/headerb\x06proto3"

var (
	file_proto_block_header_header_proto_rawDescOnce sync.Once
	file_proto_block_header_header_proto_rawDescData []byte
)

func file_proto_block_header_header_proto_rawDescGZIP() []byte {
	file_proto_block_header_header_proto_rawDescOnce.Do(func() {
		file_proto_block_header_header_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_block_header_header_proto_rawDesc), len(file_proto_block_header_header_proto_rawDesc)))
	})
	return file_proto_block_header_header_proto_rawDescData
}

var file_proto_block_header_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_block_header_header_proto_goTypes = []any{
	(*Header)(nil), // 0: core.Header
}
var file_proto_block_header_header_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_block_header_header_proto_init() }
func file_proto_block_header_header_proto_init() {
	if File_proto_block_header_header_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_block_header_header_proto_rawDesc), len(file_proto_block_header_header_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_block_header_header_proto_goTypes,
		DependencyIndexes: file_proto_block_header_header_proto_depIdxs,
		MessageInfos:      file_proto_block_header_header_proto_msgTypes,
	}.Build()
	File_proto_block_header_header_proto = out.File
	file_proto_block_header_header_proto_goTypes = nil
	file_proto_block_header_header_proto_depIdxs = nil
}
