// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/network/message/pbft.proto

package message

import (
	block "github.com/andantan/p2p-pbft-modular-blockchain-network/proto/core/block"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PbftPrePrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Block         *block.Block           `protobuf:"bytes,3,opt,name=block,proto3" json:"block,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftPrePrepareMessage) Reset() {
	*x = PbftPrePrepareMessage{}
	mi := &file_proto_network_message_pbft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftPrePrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftPrePrepareMessage) ProtoMessage() {}

func (x *PbftPrePrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_message_pbft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftPrePrepareMessage.ProtoReflect.Descriptor instead.
func (*PbftPrePrepareMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_message_pbft_proto_rawDescGZIP(), []int{0}
}

func (x *PbftPrePrepareMessage) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PbftPrePrepareMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PbftPrePrepareMessage) GetBlock() *block.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *PbftPrePrepareMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PbftPrePrepareMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PbftPrepareMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftPrepareMessage) Reset() {
	*x = PbftPrepareMessage{}
	mi := &file_proto_network_message_pbft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftPrepareMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftPrepareMessage) ProtoMessage() {}

func (x *PbftPrepareMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_message_pbft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftPrepareMessage.ProtoReflect.Descriptor instead.
func (*PbftPrepareMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_message_pbft_proto_rawDescGZIP(), []int{1}
}

func (x *PbftPrepareMessage) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PbftPrepareMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PbftPrepareMessage) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *PbftPrepareMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PbftPrepareMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type PbftCommitMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          uint64                 `protobuf:"varint,1,opt,name=view,proto3" json:"view,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PbftCommitMessage) Reset() {
	*x = PbftCommitMessage{}
	mi := &file_proto_network_message_pbft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PbftCommitMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PbftCommitMessage) ProtoMessage() {}

func (x *PbftCommitMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_message_pbft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PbftCommitMessage.ProtoReflect.Descriptor instead.
func (*PbftCommitMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_message_pbft_proto_rawDescGZIP(), []int{2}
}

func (x *PbftCommitMessage) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *PbftCommitMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PbftCommitMessage) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *PbftCommitMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PbftCommitMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_proto_network_message_pbft_proto protoreflect.FileDescriptor

const file_proto_network_message_pbft_proto_rawDesc = "" +
	"\n" +
	" proto/network/message/pbft.proto\x12\amessage\x1a\x1cproto/core/block/block.proto\"\xa8\x01\n" +
	"\x15PbftPrePrepareMessage\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\"\n" +
	"\x05block\x18\x03 \x01(\v2\f.block.BlockR\x05block\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\xa0\x01\n" +
	"\x12PbftPrepareMessage\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\fR\tblockHash\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\x9f\x01\n" +
	"\x11PbftCommitMessage\x12\x12\n" +
	"\x04view\x18\x01 \x01(\x04R\x04view\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\fR\tblockHash\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignatureBOZMgithub.com/andantan/p2p-pbft-modular-blockchain-network/proto/network/messageb\x06proto3"

var (
	file_proto_network_message_pbft_proto_rawDescOnce sync.Once
	file_proto_network_message_pbft_proto_rawDescData []byte
)

func file_proto_network_message_pbft_proto_rawDescGZIP() []byte {
	file_proto_network_message_pbft_proto_rawDescOnce.Do(func() {
		file_proto_network_message_pbft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_network_message_pbft_proto_rawDesc), len(file_proto_network_message_pbft_proto_rawDesc)))
	})
	return file_proto_network_message_pbft_proto_rawDescData
}

var file_proto_network_message_pbft_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_network_message_pbft_proto_goTypes = []any{
	(*PbftPrePrepareMessage)(nil), // 0: message.PbftPrePrepareMessage
	(*PbftPrepareMessage)(nil),    // 1: message.PbftPrepareMessage
	(*PbftCommitMessage)(nil),     // 2: message.PbftCommitMessage
	(*block.Block)(nil),           // 3: block.Block
}
var file_proto_network_message_pbft_proto_depIdxs = []int32{
	3, // 0: message.PbftPrePrepareMessage.block:type_name -> block.Block
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_network_message_pbft_proto_init() }
func file_proto_network_message_pbft_proto_init() {
	if File_proto_network_message_pbft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_network_message_pbft_proto_rawDesc), len(file_proto_network_message_pbft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_network_message_pbft_proto_goTypes,
		DependencyIndexes: file_proto_network_message_pbft_proto_depIdxs,
		MessageInfos:      file_proto_network_message_pbft_proto_msgTypes,
	}.Build()
	File_proto_network_message_pbft_proto = out.File
	file_proto_network_message_pbft_proto_goTypes = nil
	file_proto_network_message_pbft_proto_depIdxs = nil
}
