// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/network/message/sync.proto

package message

import (
	block "github.com/andantan/modular-blockchain/proto/core/block"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestStatusMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestStatusMessage) Reset() {
	*x = RequestStatusMessage{}
	mi := &file_proto_network_message_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStatusMessage) ProtoMessage() {}

func (x *RequestStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_message_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStatusMessage.ProtoReflect.Descriptor instead.
func (*RequestStatusMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_message_sync_proto_rawDescGZIP(), []int{0}
}

type ResponseStatusMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Address          []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	NetAddr          string                 `protobuf:"bytes,2,opt,name=net_addr,json=netAddr,proto3" json:"net_addr,omitempty"`
	Version          uint32                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Height           uint64                 `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	State            uint32                 `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	GenesisBlockHash []byte                 `protobuf:"bytes,6,opt,name=genesis_block_hash,json=genesisBlockHash,proto3" json:"genesis_block_hash,omitempty"`
	CurrentBlockHash []byte                 `protobuf:"bytes,7,opt,name=current_block_hash,json=currentBlockHash,proto3" json:"current_block_hash,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResponseStatusMessage) Reset() {
	*x = ResponseStatusMessage{}
	mi := &file_proto_network_message_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStatusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStatusMessage) ProtoMessage() {}

func (x *ResponseStatusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_message_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStatusMessage.ProtoReflect.Descriptor instead.
func (*ResponseStatusMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_message_sync_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseStatusMessage) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ResponseStatusMessage) GetNetAddr() string {
	if x != nil {
		return x.NetAddr
	}
	return ""
}

func (x *ResponseStatusMessage) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ResponseStatusMessage) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ResponseStatusMessage) GetState() uint32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *ResponseStatusMessage) GetGenesisBlockHash() []byte {
	if x != nil {
		return x.GenesisBlockHash
	}
	return nil
}

func (x *ResponseStatusMessage) GetCurrentBlockHash() []byte {
	if x != nil {
		return x.CurrentBlockHash
	}
	return nil
}

type RequestHeadersMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestHeadersMessage) Reset() {
	*x = RequestHeadersMessage{}
	mi := &file_proto_network_message_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestHeadersMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHeadersMessage) ProtoMessage() {}

func (x *RequestHeadersMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_message_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHeadersMessage.ProtoReflect.Descriptor instead.
func (*RequestHeadersMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_message_sync_proto_rawDescGZIP(), []int{2}
}

func (x *RequestHeadersMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RequestHeadersMessage) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ResponseHeadersMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headers       []*block.Header        `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseHeadersMessage) Reset() {
	*x = ResponseHeadersMessage{}
	mi := &file_proto_network_message_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseHeadersMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseHeadersMessage) ProtoMessage() {}

func (x *ResponseHeadersMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_message_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseHeadersMessage.ProtoReflect.Descriptor instead.
func (*ResponseHeadersMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_message_sync_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseHeadersMessage) GetHeaders() []*block.Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

type RequestBlocksMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint64                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBlocksMessage) Reset() {
	*x = RequestBlocksMessage{}
	mi := &file_proto_network_message_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBlocksMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBlocksMessage) ProtoMessage() {}

func (x *RequestBlocksMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_message_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBlocksMessage.ProtoReflect.Descriptor instead.
func (*RequestBlocksMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_message_sync_proto_rawDescGZIP(), []int{4}
}

func (x *RequestBlocksMessage) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *RequestBlocksMessage) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ResponseBlocksMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*block.Block         `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseBlocksMessage) Reset() {
	*x = ResponseBlocksMessage{}
	mi := &file_proto_network_message_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBlocksMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBlocksMessage) ProtoMessage() {}

func (x *ResponseBlocksMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_message_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBlocksMessage.ProtoReflect.Descriptor instead.
func (*ResponseBlocksMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_message_sync_proto_rawDescGZIP(), []int{5}
}

func (x *ResponseBlocksMessage) GetBlocks() []*block.Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_proto_network_message_sync_proto protoreflect.FileDescriptor

const file_proto_network_message_sync_proto_rawDesc = "" +
	"\n" +
	" proto/network/message/sync.proto\x12\amessage\x1a\x1cproto/core/block/block.proto\x1a\x1dproto/core/block/header.proto\"\x16\n" +
	"\x14RequestStatusMessage\"\xf0\x01\n" +
	"\x15ResponseStatusMessage\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\fR\aaddress\x12\x19\n" +
	"\bnet_addr\x18\x02 \x01(\tR\anetAddr\x12\x18\n" +
	"\aversion\x18\x03 \x01(\rR\aversion\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x04R\x06height\x12\x14\n" +
	"\x05state\x18\x05 \x01(\rR\x05state\x12,\n" +
	"\x12genesis_block_hash\x18\x06 \x01(\fR\x10genesisBlockHash\x12,\n" +
	"\x12current_block_hash\x18\a \x01(\fR\x10currentBlockHash\"A\n" +
	"\x15RequestHeadersMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"A\n" +
	"\x16ResponseHeadersMessage\x12'\n" +
	"\aheaders\x18\x01 \x03(\v2\r.block.HeaderR\aheaders\"@\n" +
	"\x14RequestBlocksMessage\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x04R\x04from\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\"=\n" +
	"\x15ResponseBlocksMessage\x12$\n" +
	"\x06blocks\x18\x01 \x03(\v2\f.block.BlockR\x06blocksB>Z<github.com/andantan/modular-blockchain/proto/network/messageb\x06proto3"

var (
	file_proto_network_message_sync_proto_rawDescOnce sync.Once
	file_proto_network_message_sync_proto_rawDescData []byte
)

func file_proto_network_message_sync_proto_rawDescGZIP() []byte {
	file_proto_network_message_sync_proto_rawDescOnce.Do(func() {
		file_proto_network_message_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_network_message_sync_proto_rawDesc), len(file_proto_network_message_sync_proto_rawDesc)))
	})
	return file_proto_network_message_sync_proto_rawDescData
}

var file_proto_network_message_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_network_message_sync_proto_goTypes = []any{
	(*RequestStatusMessage)(nil),   // 0: message.RequestStatusMessage
	(*ResponseStatusMessage)(nil),  // 1: message.ResponseStatusMessage
	(*RequestHeadersMessage)(nil),  // 2: message.RequestHeadersMessage
	(*ResponseHeadersMessage)(nil), // 3: message.ResponseHeadersMessage
	(*RequestBlocksMessage)(nil),   // 4: message.RequestBlocksMessage
	(*ResponseBlocksMessage)(nil),  // 5: message.ResponseBlocksMessage
	(*block.Header)(nil),           // 6: block.Header
	(*block.Block)(nil),            // 7: block.Block
}
var file_proto_network_message_sync_proto_depIdxs = []int32{
	6, // 0: message.ResponseHeadersMessage.headers:type_name -> block.Header
	7, // 1: message.ResponseBlocksMessage.blocks:type_name -> block.Block
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_network_message_sync_proto_init() }
func file_proto_network_message_sync_proto_init() {
	if File_proto_network_message_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_network_message_sync_proto_rawDesc), len(file_proto_network_message_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_network_message_sync_proto_goTypes,
		DependencyIndexes: file_proto_network_message_sync_proto_depIdxs,
		MessageInfos:      file_proto_network_message_sync_proto_msgTypes,
	}.Build()
	File_proto_network_message_sync_proto = out.File
	file_proto_network_message_sync_proto_goTypes = nil
	file_proto_network_message_sync_proto_depIdxs = nil
}
