// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/core/block/block.proto

package block

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Block struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockHash     []byte                 `protobuf:"bytes,1,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Header        *Header                `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Body          *Body                  `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Tail          *Tail                  `protobuf:"bytes,4,opt,name=tail,proto3" json:"tail,omitempty"`
	Proposer      []byte                 `protobuf:"bytes,5,opt,name=proposer,proto3" json:"proposer,omitempty"`
	Signature     []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Block) Reset() {
	*x = Block{}
	mi := &file_proto_core_block_block_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_proto_core_block_block_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_proto_core_block_block_proto_rawDescGZIP(), []int{0}
}

func (x *Block) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *Block) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Block) GetBody() *Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Block) GetTail() *Tail {
	if x != nil {
		return x.Tail
	}
	return nil
}

func (x *Block) GetProposer() []byte {
	if x != nil {
		return x.Proposer
	}
	return nil
}

func (x *Block) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_proto_core_block_block_proto protoreflect.FileDescriptor

const file_proto_core_block_block_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/core/block/block.proto\x12\x05block\x1a\x1dproto/core/block/header.proto\x1a\x1bproto/core/block/body.proto\x1a\x1bproto/core/block/tail.proto\"\xc9\x01\n" +
	"\x05Block\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x01 \x01(\fR\tblockHash\x12%\n" +
	"\x06header\x18\x02 \x01(\v2\r.block.HeaderR\x06header\x12\x1f\n" +
	"\x04body\x18\x03 \x01(\v2\v.block.BodyR\x04body\x12\x1f\n" +
	"\x04tail\x18\x04 \x01(\v2\v.block.TailR\x04tail\x12\x1a\n" +
	"\bproposer\x18\x05 \x01(\fR\bproposer\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignatureB9Z7github.com/andantan/modular-blockchain/proto/core/blockb\x06proto3"

var (
	file_proto_core_block_block_proto_rawDescOnce sync.Once
	file_proto_core_block_block_proto_rawDescData []byte
)

func file_proto_core_block_block_proto_rawDescGZIP() []byte {
	file_proto_core_block_block_proto_rawDescOnce.Do(func() {
		file_proto_core_block_block_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_core_block_block_proto_rawDesc), len(file_proto_core_block_block_proto_rawDesc)))
	})
	return file_proto_core_block_block_proto_rawDescData
}

var file_proto_core_block_block_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_core_block_block_proto_goTypes = []any{
	(*Block)(nil),  // 0: block.Block
	(*Header)(nil), // 1: block.Header
	(*Body)(nil),   // 2: block.Body
	(*Tail)(nil),   // 3: block.Tail
}
var file_proto_core_block_block_proto_depIdxs = []int32{
	1, // 0: block.Block.header:type_name -> block.Header
	2, // 1: block.Block.body:type_name -> block.Body
	3, // 2: block.Block.tail:type_name -> block.Tail
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_core_block_block_proto_init() }
func file_proto_core_block_block_proto_init() {
	if File_proto_core_block_block_proto != nil {
		return
	}
	file_proto_core_block_header_proto_init()
	file_proto_core_block_body_proto_init()
	file_proto_core_block_tail_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_core_block_block_proto_rawDesc), len(file_proto_core_block_block_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_core_block_block_proto_goTypes,
		DependencyIndexes: file_proto_core_block_block_proto_depIdxs,
		MessageInfos:      file_proto_core_block_block_proto_msgTypes,
	}.Build()
	File_proto_core_block_block_proto = out.File
	file_proto_core_block_block_proto_goTypes = nil
	file_proto_core_block_block_proto_depIdxs = nil
}
