// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/network/protocol/tcp/handshake.proto

package tcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TcpHandshakeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     []byte                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	NetAddr       string                 `protobuf:"bytes,2,opt,name=net_addr,json=netAddr,proto3" json:"net_addr,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TcpHandshakeMessage) Reset() {
	*x = TcpHandshakeMessage{}
	mi := &file_proto_network_protocol_tcp_handshake_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TcpHandshakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TcpHandshakeMessage) ProtoMessage() {}

func (x *TcpHandshakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_network_protocol_tcp_handshake_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TcpHandshakeMessage.ProtoReflect.Descriptor instead.
func (*TcpHandshakeMessage) Descriptor() ([]byte, []int) {
	return file_proto_network_protocol_tcp_handshake_proto_rawDescGZIP(), []int{0}
}

func (x *TcpHandshakeMessage) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *TcpHandshakeMessage) GetNetAddr() string {
	if x != nil {
		return x.NetAddr
	}
	return ""
}

func (x *TcpHandshakeMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

var File_proto_network_protocol_tcp_handshake_proto protoreflect.FileDescriptor

const file_proto_network_protocol_tcp_handshake_proto_rawDesc = "" +
	"\n" +
	"*proto/network/protocol/tcp/handshake.proto\x12\x03tcp\"m\n" +
	"\x13TcpHandshakeMessage\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\fR\tpublicKey\x12\x19\n" +
	"\bnet_addr\x18\x02 \x01(\tR\anetAddr\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignatureBTZRgithub.com/andantan/p2p-pbft-modular-blockchain-network/proto/network/protocol/tcpb\x06proto3"

var (
	file_proto_network_protocol_tcp_handshake_proto_rawDescOnce sync.Once
	file_proto_network_protocol_tcp_handshake_proto_rawDescData []byte
)

func file_proto_network_protocol_tcp_handshake_proto_rawDescGZIP() []byte {
	file_proto_network_protocol_tcp_handshake_proto_rawDescOnce.Do(func() {
		file_proto_network_protocol_tcp_handshake_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_network_protocol_tcp_handshake_proto_rawDesc), len(file_proto_network_protocol_tcp_handshake_proto_rawDesc)))
	})
	return file_proto_network_protocol_tcp_handshake_proto_rawDescData
}

var file_proto_network_protocol_tcp_handshake_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_network_protocol_tcp_handshake_proto_goTypes = []any{
	(*TcpHandshakeMessage)(nil), // 0: tcp.TcpHandshakeMessage
}
var file_proto_network_protocol_tcp_handshake_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_network_protocol_tcp_handshake_proto_init() }
func file_proto_network_protocol_tcp_handshake_proto_init() {
	if File_proto_network_protocol_tcp_handshake_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_network_protocol_tcp_handshake_proto_rawDesc), len(file_proto_network_protocol_tcp_handshake_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_network_protocol_tcp_handshake_proto_goTypes,
		DependencyIndexes: file_proto_network_protocol_tcp_handshake_proto_depIdxs,
		MessageInfos:      file_proto_network_protocol_tcp_handshake_proto_msgTypes,
	}.Build()
	File_proto_network_protocol_tcp_handshake_proto = out.File
	file_proto_network_protocol_tcp_handshake_proto_goTypes = nil
	file_proto_network_protocol_tcp_handshake_proto_depIdxs = nil
}
